FROM golang:1.22-alpine as builder

WORKDIR /app

COPY . .
RUN go mod download
RUN go mod tidy
RUN go build -o bin/myru-streaming cmd/server/main.go


FROM keymetrics/pm2:18-alpine

WORKDIR /app

COPY --from=builder  /app/bin/myru-streaming .
RUN chmod ++x /app/myru-streaming

CMD ["pm2-runtime", "myru-streaming"]