services:
  app:
    image: 058264421407.dkr.ecr.us-west-2.amazonaws.com/myru-frontend
    restart: on-failure:5
    volumes:
      - ./.env.production:/app/.env.production
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    ports:
      - 81:3000
